name: speedx-rnaseq
channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bioconductor-deseq
- bioconda::bowtie2=2.5.4
- bioconda::cutadapt=4.9
- bioconda::fastqc=0.12.1
- bioconda::htseq=2.0.5
- bioconda::samtools=1.21
- r-base
- r-pheatmap
- r-rcolorbrewer
- r-biocmanager
- bioconductor-deseq2
- bioconductor-apeglm